version: '2'
services:
  web:
    build: .
    ports:
      - "8080:5001"
      - "8083:443"
    environment:
      - DATABASE_URL=postgres://postgres:mistakeSJournal@host.docker.internal/mistakes_journal
    depends_on:
      - db
    networks:
      - api
  db:
    image: postgres:latest
    environment:
    - POSTGRES_PASSWORD=mistakeSJournal
    - POSTGRES_DB=mistakes_journal
    ports:
      - "5432:5432"
    networks:
      - api

networks:
  api:
    driver: bridge

