//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mistakes.Journal.Api.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccountResource_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResource_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Mistakes.Journal.Api.Resources.AccountResource_en", typeof(AccountResource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppTitleFirst {
            get {
                return ResourceManager.GetString("AppTitleFirst", resourceCulture);
            }
        }
        
        internal static string AppTitleSecond {
            get {
                return ResourceManager.GetString("AppTitleSecond", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string LoginTitleFirst {
            get {
                return ResourceManager.GetString("LoginTitleFirst", resourceCulture);
            }
        }
        
        internal static string LoginTitleSecond {
            get {
                return ResourceManager.GetString("LoginTitleSecond", resourceCulture);
            }
        }
        
        internal static string FirstTime {
            get {
                return ResourceManager.GetString("FirstTime", resourceCulture);
            }
        }
        
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string ErrorPasswordIncorrect {
            get {
                return ResourceManager.GetString("ErrorPasswordIncorrect", resourceCulture);
            }
        }
        
        internal static string ErrorPasswordRequired {
            get {
                return ResourceManager.GetString("ErrorPasswordRequired", resourceCulture);
            }
        }
        
        internal static string ErrorEmailAddress {
            get {
                return ResourceManager.GetString("ErrorEmailAddress", resourceCulture);
            }
        }
        
        internal static string ErrorRequiredEmail {
            get {
                return ResourceManager.GetString("ErrorRequiredEmail", resourceCulture);
            }
        }
        
        internal static string ErrorUserNotFound {
            get {
                return ResourceManager.GetString("ErrorUserNotFound", resourceCulture);
            }
        }
        
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        internal static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        internal static string GDPR {
            get {
                return ResourceManager.GetString("GDPR", resourceCulture);
            }
        }
        
        internal static string RegisterTitleFirst {
            get {
                return ResourceManager.GetString("RegisterTitleFirst", resourceCulture);
            }
        }
        
        internal static string RegisterTitleSecond {
            get {
                return ResourceManager.GetString("RegisterTitleSecond", resourceCulture);
            }
        }
        
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        internal static string PasswordHint {
            get {
                return ResourceManager.GetString("PasswordHint", resourceCulture);
            }
        }
        
        internal static string AgreeToNewsletter {
            get {
                return ResourceManager.GetString("AgreeToNewsletter", resourceCulture);
            }
        }
        
        internal static string SignUpAgreementFirst {
            get {
                return ResourceManager.GetString("SignUpAgreementFirst", resourceCulture);
            }
        }
        
        internal static string SignUpAgreementSecond {
            get {
                return ResourceManager.GetString("SignUpAgreementSecond", resourceCulture);
            }
        }
        
        internal static string AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAccount", resourceCulture);
            }
        }
        
        internal static string NoAccess {
            get {
                return ResourceManager.GetString("NoAccess", resourceCulture);
            }
        }
        
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        internal static string ErrorPasswordNoMatch {
            get {
                return ResourceManager.GetString("ErrorPasswordNoMatch", resourceCulture);
            }
        }
        
        internal static string ErrorAgeRequired {
            get {
                return ResourceManager.GetString("ErrorAgeRequired", resourceCulture);
            }
        }
        
        internal static string ErrorCountryRequired {
            get {
                return ResourceManager.GetString("ErrorCountryRequired", resourceCulture);
            }
        }
        
        internal static string ErrorRequiredNewsletter {
            get {
                return ResourceManager.GetString("ErrorRequiredNewsletter", resourceCulture);
            }
        }
    }
}
